# Generated by Django 5.2.1 on 2025-05-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_otpverification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
