# Generated by Django 5.2.1 on 2025-08-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
