# Generated by Django 5.2.1 on 2025-07-03 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category-icons/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Base Class',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('MALA', 'Mala / Tulsi Kanthi'), ('JAPA', 'Japa Beads / Bags'), ('TILAK', 'Tilak / Gopi Chandan'), ('CHANDAN', 'Chandan Paste / Powder'), ('BOOK', 'Books (Spiritual / Srila Prabhupada)'), ('DECOR', 'Temple Decor / Home Altar Items'), ('MUSIC', 'Spiritual CDs / Kirtan'), ('DRESS', 'Deity Dresses / Accessories'), ('PUJA', 'Puja Samagri / Aarti Items'), ('ABHISHEK', 'Abhishek Items / Panchamrit Sets'), ('FOOD', 'Dry Fruits / Bhog Items / Mishri'), ('GIFT', 'Spiritual Gifts / Hampers'), ('UTENSILS', 'Copper / Brass Puja Utensils'), ('FESTIVAL', 'Ekadashi / Janmashtami Items'), ('OTHER', 'Other Items')], default='OTHER', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(unique=True)),
                ('source_website', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ProductsManagement.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ProductsManagement.product')),
            ],
            options={
                'verbose_name': 'Base Class',
                'abstract': False,
            },
        ),
    ]
