# Generated by Django 5.2.1 on 2025-07-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
