# Generated by Django 5.2.1 on 2025-07-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsManagement', '0002_alter_product_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
